// Generated by CoffeeScript 1.10.0
(function() {
  var Builder;

  Builder = (function() {
    function Builder(wz) {
      this.wz = wz;
      this.cfg = this.wz.cfg;
    }

    Builder.prototype.build = function() {
      return console.log('build');
    };

    return Builder;

  })();

  module.exports = Builder;

}).call(this);

//# sourceMappingURL=builder.js.map
