// Generated by CoffeeScript 1.10.0
(function() {
  var Config, FSU, Home, Path, _;

  Path = require('path');

  FSU = require('./utils/fsu');

  Home = require('homedir');

  _ = require('./utils/pimped-lodash');

  Config = (function() {
    function Config(base, cfgOrPath) {
      var cfg, def;
      this.base = base;
      if (_.isString(cfgOrPath)) {
        cfg = FSU.require(Path.join(this.base, cfgOrPath));
        if (!cfg) {
          cfg = FSU.require(cfgOrPath);
        }
      }
      if (!cfg) {
        cfg = FSU.require(this.base, '.werkzeug');
      }
      if (!cfg) {
        cfg = FSU.require(Home(), '.werkzeug');
      }
      def = FSU.require(__dirname, '..', '.default.werkzeug');
      _.deepMerge(this, def, cfg);
    }

    return Config;

  })();

  module.exports = Config;

}).call(this);
