// Generated by CoffeeScript 1.10.0
(function() {
  var CP, IPC, Path, SERVER, SW, Server;

  Path = require('path');

  CP = require('child_process');

  IPC = require('./utils/ipc');

  SW = require('./utils/stopwatch');

  SERVER = Path.join(__dirname, 'server', 'server-process');

  Server = (function() {
    function Server(wz) {
      this.wz = wz;
      this.initialized = false;
      this.cfg = this.wz.cfg;
    }

    Server.prototype.init = function() {
      if (this.server) {
        this.server.exit();
      }
      this.server = new IPC(CP.fork(SERVER), this);
      this.server.send('init', this.cfg);
      return null;
    };

    Server.prototype.serverReady = function(port) {
      console.log("server listening on port " + port);
      return null;
    };

    Server.prototype.exit = function() {
      if (this.server) {
        this.server.exit();
      }
      return null;
    };

    return Server;

  })();

  module.exports = Server;

}).call(this);
