// Generated by CoffeeScript 1.10.0
(function() {
  var Chok, EMap, Watcher;

  Chok = require('chokidar');

  EMap = require('emap');

  Watcher = (function() {
    function Watcher(wz) {
      this.wz = wz;
      this.cfg = this.wz.cfg;
      this.emap = new EMap();
    }

    Watcher.prototype.watch = function() {
      if (this.watcher) {
        this.emap.all();
        this.watcher.close();
      }
      this.watcher = Chok.watch(this.cfg.base, {
        ignored: [this.wz.ignores],
        ignoreInitial: false,
        usePolling: false,
        useFsEvents: true
      });
      this.emap.map(this.watcher, 'add', this.addedHandler, this);
      this.emap.map(this.watcher, 'change', this.changedHandler, this);
      this.emap.map(this.watcher, 'unlink', this.unlinkedHandler, this);
      this.emap.map(this.watcher, 'ready', this.readyHandler, this);
      return null;
    };

    Watcher.prototype.addedHandler = function(path) {
      this.wz.fileAdded(path);
      return null;
    };

    Watcher.prototype.changedHandler = function(path) {
      this.wz.fileChanged(path);
      return null;
    };

    Watcher.prototype.unlinkedHandler = function(path) {
      this.wz.fileRemoved(path);
      return null;
    };

    Watcher.prototype.readyHandler = function() {
      this.watching = true;
      this.wz.walked();
      return null;
    };

    return Watcher;

  })();

  module.exports = Watcher;

}).call(this);

//# sourceMappingURL=watcher.js.map
