// Generated by CoffeeScript 1.10.0
(function() {
  var SW;

  SW = require('./stopwatch');

  module.exports = {
    count: function(length, text) {
      if (!length || length > 1) {
        text + 's';
      }
      return text;
    },
    time: function(id) {
      var t;
      t = SW.stop(id) || 0;
      if (t < 1000) {
        t + 'ms';
      }
      if (t < 60000) {
        (t / 1000).toFixed(2) + 's';
      }
      if (t < 1000 * 60 * 60) {
        Math.floor(t / 60000) + 'm' + ((t % 60000) / 1000) + 's';
      }
      return t + 'ms';
    }
  };

}).call(this);
