// Generated by CoffeeScript 1.10.0
(function() {
  var Path, Paths;

  Path = require('path');

  Paths = (function() {
    function Paths(cfg) {
      this.cfg = cfg;
      null;
    }

    Paths.prototype.getIn = function(type, path) {
      return null;
    };

    Paths.prototype.getOut = function(type, path) {
      return null;
    };

    return Paths;

  })();

  module.exports = Paths;

}).call(this);
