// Generated by CoffeeScript 1.10.0
(function() {
  var _, deepExtend, deepMerge,
    slice = [].slice;

  _ = require('lodash');

  deepExtend = function(target, source) {
    var key, targetValue, value;
    for (key in source) {
      value = source[key];
      if (_.isObject(value) && target.hasOwnProperty(key)) {
        targetValue = target[key];
        if (!_.isObject(targetValue)) {
          targetValue = {};
        }
        target[key] = deepExtend(targetValue, value);
      } else {
        target[key] = value;
      }
    }
    return target;
  };

  deepMerge = function() {
    var i, len, source, sources, target;
    target = arguments[0], sources = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    for (i = 0, len = sources.length; i < len; i++) {
      source = sources[i];
      deepExtend(target, source);
    }
    return target;
  };

  _.deepExtend = deepExtend;

  _.deepMerge = deepMerge;

  module.exports = _;

}).call(this);
