// Generated by CoffeeScript 1.10.0
(function() {
  var Path, r;

  Path = require('path');

  r = {
    sass: /\.sass$|\.scss$/,
    less: /\.less$/,
    ts: /\.ts$/,
    coffee: /\.coffee$/
  };

  r.testSass = function(s) {
    return r.sass.test(s);
  };

  r.testLess = function(s) {
    return r.less.test(s);
  };

  r.testTS = function(s) {
    return r.ts.test(s);
  };

  r.testCoffee = function(s) {
    return r.coffee.test(s);
  };

  r.correctOut = function(path) {
    if (r.testSass(path)) {
      return path.replace(r.sass, '.css');
    }
    if (r.testLess(path)) {
      return path.replace(r.less, '.css');
    }
    if (r.testTS(path)) {
      return path.replace(r.ts, '.js');
    }
    if (r.testCoffee(path)) {
      return path.replace(r.coffee, '.js');
    }
    return path;
  };

  r.correctTmp = function(path, base, tmp) {
    return Path.join(tmp, Path.relative(base, path));
  };

  module.exports = r;

}).call(this);
