// Generated by CoffeeScript 1.10.0
(function() {
  var StopWatch;

  StopWatch = (function() {
    function StopWatch() {
      this.map = {};
    }

    StopWatch.prototype.start = function(id) {
      this.map[id] = Date.now();
      return null;
    };

    StopWatch.prototype.stop = function(id) {
      var now, start;
      now = Date.now();
      start = this.map[id] || now;
      return now - start;
    };

    return StopWatch;

  })();

  module.exports = new StopWatch();

}).call(this);
