// Generated by CoffeeScript 1.10.0
(function() {
  var AssetCompiler, FS, FSU, IPC, PH;

  FS = require('fs-extra');

  FSU = require('../utils/fsu');

  IPC = require('../utils/ipc');

  PH = require('../utils/path-helper');

  AssetCompiler = (function() {
    function AssetCompiler() {
      this.cfg = null;
      this.errors = null;
      this.openFiles = 0;
      this.ipc = new IPC(process, this);
    }

    AssetCompiler.prototype.init = function(cfg) {
      this.cfg = cfg;
      return null;
    };

    AssetCompiler.prototype.compile = function(files) {
      var file, i, len, out, path;
      this.errors = [];
      this.openFiles = 0;
      for (i = 0, len = files.length; i < len; i++) {
        file = files[i];
        ++this.openFiles;
        path = file.path;
        out = PH.outFromIn(this.cfg, 'assets', path);
        if (!file.removed) {
          this.copy(path, out);
        } else {
          this.remove(path, out);
        }
      }
      if (!this.openFiles) {
        this.compiled();
      }
      return null;
    };

    AssetCompiler.prototype.copy = function(path, out) {
      console.log('copy asset: ', path, out);
      FS.copy(path, out, (function(_this) {
        return function(error) {
          --_this.openFiles;
          if (error) {
            _this.errors.push({
              path: path,
              error: error
            });
          }
          if (_this.openFiles === 0) {
            _this.compiled();
          }
          return null;
        };
      })(this));
      return null;
    };

    AssetCompiler.prototype.remove = function(path, out) {
      var map;
      console.log('remove asset: ', path, out);
      out = PH.correctOut(out);
      map = out + '.map';
      FS.remove(out, (function(_this) {
        return function(error) {
          --_this.openFiles;
          if (FSU.isFile(map)) {
            ++_this.openFiles;
            FS.remove(map, function(error) {
              --_this.openFiles;
              if (error) {
                _this.errors.push({
                  path: map,
                  error: error
                });
              }
              if (_this.openFiles === 0) {
                _this.compiled();
              }
              return null;
            });
          }
          if (error) {
            _this.errors.push({
              path: out,
              error: error
            });
          }
          if (_this.openFiles === 0) {
            _this.compiled();
          }
          return null;
        };
      })(this));
      return null;
    };

    AssetCompiler.prototype.compiled = function() {
      return this.ipc.send('compiled', 'assets', this.errors);
    };

    return AssetCompiler;

  })();

  module.exports = new AssetCompiler();

}).call(this);
