// Generated by CoffeeScript 1.10.0
(function() {
  var CoffeeCompiler, FSU, IPC, coffee, fs, options;

  coffee = require('coffee-script');

  fs = require('fs');

  FSU = require('../utils/fsu');

  IPC = require('../utils/ipc');

  options = {
    sourceMap: true,
    inlineMap: false,
    filename: ''
  };

  CoffeeCompiler = (function() {
    function CoffeeCompiler() {}

    return CoffeeCompiler;

  })();

}).call(this);

//# sourceMappingURL=coffee.js.map
