// Generated by CoffeeScript 1.10.0
(function() {
  var FS, IPC, Path, Reg, Sass, SassCompiler, options,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Path = require('path');

  FS = require('fs-extra');

  Sass = require('node-sass');

  Reg = require('../utils/regex');

  IPC = require('../utils/ipc');

  options = {
    'style': 'nested',
    'stop-on-error': false,
    'sourcemap': 'auto',
    'default-encoding': 'utf-8',
    'check': true,
    'precision': 5,
    'cache-location': '',
    'quiet': false
  };

  SassCompiler = (function() {
    function SassCompiler() {
      this.onResult = bind(this.onResult, this);
      this.initialized = false;
      this.cfg = null;
      this.errors = null;
      this.openFiles = 0;
      this.ipc = new IPC(process, this);
    }

    SassCompiler.prototype.init = function(cfg) {
      this.cfg = cfg;
      options['cache-location'] = Path.join(this.cfg.base, this.cfg.tmp, '.sass-cache');
      return null;
    };

    SassCompiler.prototype.compile = function(files) {
      var base, file, i, len, out, path, tmp;
      this.errors = [];
      options = {
        outputStyle: 'compressed',
        sourceMap: true
      };
      base = this.cfg.base;
      tmp = this.cfg.tmp;
      for (i = 0, len = files.length; i < len; i++) {
        file = files[i];
        path = file.path;
        if (!/^_/.test(Path.basename(path))) {
          ++this.openFiles;
          out = Reg.correctTmp(path, base, tmp);
          options.file = path;
          options.outFile = Reg.correctOut(out);
          Sass.render(options, this.onResult);
        }
      }
      return null;
    };

    SassCompiler.prototype.onResult = function(error, result) {
      var base, map, out, path, tmp;
      --this.openFiles;
      if (error) {
        this.errors.push({
          path: error.file,
          line: error.line,
          col: error.column,
          text: error.message
        });
      } else {
        base = this.cfg.base;
        tmp = this.cfg.tmp;
        path = result.stats.entry;
        out = Reg.correctTmp(Reg.correctOut(path), base, tmp);
        map = out + '.map';
        FS.ensureFileSync(out);
        FS.ensureFileSync(map);
        FS.writeFileSync(out, result.css, 'utf8');
        FS.writeFileSync(map, result.map, 'utf8');
      }
      if (this.openFiles === 0) {
        this.compiled();
      }
      return null;
    };

    SassCompiler.prototype.compiled = function() {
      this.initialized = true;
      return this.ipc.send('compiled', 'sass', this.errors);
    };

    return SassCompiler;

  })();

  module.exports = new SassCompiler();

}).call(this);
